"""
NCAIR-DSA — Gradio entry point.
Pipeline: audio capture -> ASR -> lightweight language/code-switching
detection -> N-ATLaS structuring (clinical note + possible recommendations)
-> keyword extraction -> review (tabbed) -> patient record save.

Main goal: full structured English clinical note (removes translation barrier).
Tab hierarchy (per supervisor's request):
  1. Clinical Note        — MOST prominent, default tab, editable, grounded facts only
  2. Possible Recommendations — second-tier, editable, conservative/hedged AI nudge
  3. Keywords              — minor tab, read-only, de-emphasized quick reference

NOTE: Google Drive must be mounted BEFORE running this script, from a
notebook cell — not from inside app.py. drive.mount() needs Colab's
interactive kernel to show the auth popup; running `!python app.py`
executes this as a subprocess with no kernel attached.
In your Colab notebook, run this in its own cell FIRST:
    from google.colab import drive
    drive.mount('/content/drive')
THEN run: !python app.py
"""
import gradio as gr
import json

from asr.transcribe import transcribe_audio
from nlp.structure_note import structure_note
from nlp.extract_keywords import extract_keywords
from nlp.language_detect import detect_code_switching
from templates.clinical_note import init_db, save_patient_record as db_save_patient_record, get_patient_history

# Ensure database tables exist on startup
init_db()

# Hardcoded disclaimer — NOT generated by the LLM, so it can never be
# accidentally dropped or forgotten in a given output. Always prepended
# in code before the possible_recommendations field is displayed.
RECOMMENDATIONS_DISCLAIMER = (
    "⚠️ For doctor consideration only — NOT a diagnosis. "
    "This is a model-generated suggestion and may be incomplete or inaccurate. "
    "Clinical judgment should always take precedence.\n\n"
)

SEVERITY_COLORS = {
    "mild": "#2e7d32",      # green
    "moderate": "#ef6c00",  # amber
    "severe": "#c62828",    # red
}


def severity_badge_html(severity_text: str) -> str:
    """Render a small color-coded badge based on severity keyword found in the text."""
    if not severity_text:
        return ""
    lowered = severity_text.lower()
    color = "#666666"
    label = "Unspecified"
    for key, hex_color in SEVERITY_COLORS.items():
        if key in lowered:
            color = hex_color
            label = key.capitalize()
            break
    return (
        f'<div style="display:inline-block; padding:4px 14px; border-radius:14px; '
        f'background-color:{color}; color:white; font-weight:600; font-size:0.85em;">'
        f'{label}</div>'
    )


def process_patient_intake(patient_id, language, audio_file):
    """
    End-to-end pipeline:
    1. Transcribe audio to text
    2. Lightweight language/code-switching detection (offloads work from N-ATLaS)
    3. Structure into full English clinical note + possible recommendations
    4. Extract keywords from the ENGLISH note (not raw transcript)
    5. Return everything needed for the tabbed review UI
    """
    if not audio_file or not patient_id:
        return "", "", "", "", "", "", "", "", "{}", "Error: Patient ID and audio required"

    # --- Step 1: Transcribe ---
    try:
        transcript = transcribe_audio(audio_file, language)
    except Exception as e:
        return "", "", "", "", "", "", "", "", "{}", f"Error transcribing audio: {str(e)}"

    # --- Step 2: Lightweight language/code-switching detection ---
    lang_info = detect_code_switching(transcript, expected_language=language)

    # --- Step 3: Structure into clinical note (MAIN deliverable) ---
    note = structure_note(transcript, language_context=lang_info["context_note"])

    if note.get("_error"):
        status = f"⚠ Note generated with issues: {note['_error']}"
    else:
        status = "✓ Ready for review"
        if lang_info["likely_code_switched"]:
            status += " — note: possible code-switching detected in audio"

    # --- Step 4: Extract keywords from the ENGLISH structured note ---
    # (not the raw transcript, which may be in Hausa/Igbo/Yoruba)
    english_note_text = " ".join([
        note.get("chief_complaint", ""),
        note.get("duration", ""),
        note.get("severity", ""),
        note.get("history", ""),
    ])
    keywords = extract_keywords(english_note_text)

    keywords_text = f"""Symptoms Detected:
{', '.join(keywords.get('symptoms', [])) if keywords.get('symptoms') else 'None'}

Duration Mentions:
{', '.join(keywords.get('duration', [])) if keywords.get('duration') else 'None'}

Severity Language:
{', '.join(keywords.get('severity', [])) if keywords.get('severity') else 'None'}

Anatomical Sites:
{', '.join(keywords.get('anatomical_sites', [])) if keywords.get('anatomical_sites') else 'None'}
"""

    severity_html = severity_badge_html(note.get("severity", ""))
    recommendations_with_disclaimer = RECOMMENDATIONS_DISCLAIMER + note.get("possible_recommendations", "")

    return (
        note.get("chief_complaint", ""),
        note.get("duration", ""),
        note.get("severity", ""),
        note.get("history", ""),
        severity_html,
        recommendations_with_disclaimer,
        keywords_text,
        transcript,                    # hidden state — needed at save time
        json.dumps(keywords),          # hidden state — needed at save time
        status,
    )


def handle_save_click(patient_id, language, chief_complaint, duration, severity, history,
                       recommendations_text, transcript_state, keywords_state_json):
    """Gradio click handler for saving the (doctor-reviewed) record to the database."""
    if not patient_id:
        return "Error: Patient ID is required to save"

    try:
        keywords = json.loads(keywords_state_json) if keywords_state_json else {}

        # Strip the hardcoded disclaimer back off before saving, so it's not
        # duplicated every time this record is displayed again later
        recommendations_to_save = recommendations_text
        if recommendations_to_save.startswith(RECOMMENDATIONS_DISCLAIMER):
            recommendations_to_save = recommendations_to_save[len(RECOMMENDATIONS_DISCLAIMER):]

        db_save_patient_record(
            patient_id=patient_id,
            chief_complaint=chief_complaint,
            duration=duration,
            severity=severity,
            history=history,
            possible_recommendations=recommendations_to_save,
            language=language,
            keywords=keywords,
            transcript=transcript_state,
        )
        return f"✓ Patient {patient_id} record saved successfully"
    except Exception as e:
        return f"✗ Error saving record: {str(e)}"


def handle_view_history_click(patient_id):
    """Look up and display a patient's past visits."""
    if not patient_id:
        return "Enter a Patient ID to view history"

    visits = get_patient_history(patient_id)

    if not visits:
        return f"No previous visits found for patient {patient_id}"

    lines = [f"History for {patient_id} ({len(visits)} visit(s)):\n"]
    for visit in visits:
        visit_id, chief_complaint, duration, severity, history, recommendations, language, created_at = visit
        lines.append(
            f"— {created_at} [{language}]\n"
            f"  Complaint: {chief_complaint}\n"
            f"  Duration: {duration}\n"
            f"  Severity: {severity}\n"
            f"  History: {history}\n"
            f"  Recommendations: {recommendations}\n"
        )
    return "\n".join(lines)


# ============================================================================
# Custom Theme
# ============================================================================

theme = gr.themes.Soft(
    primary_hue="teal",
    secondary_hue="blue",
    neutral_hue="slate",
    font=[gr.themes.GoogleFont("Inter"), "sans-serif"],
).set(
    button_primary_background_fill="*primary_600",
    button_primary_background_fill_hover="*primary_700",
    block_title_text_weight="600",
)


# ============================================================================
# Gradio Interface
# ============================================================================

with gr.Blocks(title="NCAIR-DSA: Patient Intake Assistant", theme=theme) as demo:
    gr.HTML(
        """
        <div style="text-align:center; padding: 12px 0 4px 0;">
            <h1 style="margin-bottom:4px;">🩺 NCAIR-DSA Patient Intake Assistant</h1>
            <p style="color:#666; font-size:1.05em;">
                Multi-lingual voice-to-clinical-note system — Hausa · Igbo · Yoruba → English
            </p>
        </div>
        """
    )

    transcript_state = gr.State("")
    keywords_state = gr.State("{}")

    # --- Step 1: Capture ---
    with gr.Group():
        gr.Markdown("### 🎙️ Step 1 — Record Patient Audio")
        with gr.Row():
            patient_id = gr.Textbox(label="Patient ID", placeholder="e.g., P001", scale=1)
            language = gr.Dropdown(choices=["Hausa", "Igbo", "Yoruba"], label="Language", scale=1)

        audio_input = gr.Audio(
            label="Patient Audio (Upload or Record)",
            type="filepath",
            sources=["upload", "microphone"]
        )

        transcribe_btn = gr.Button("🔄 Transcribe & Generate Clinical Note", variant="primary", size="lg")
        process_status = gr.Textbox(label="Status", interactive=False)

    # --- Step 2: Review — Tabbed, with clear prominence hierarchy ---
    gr.Markdown("### 📋 Step 2 — Doctor Review & Edit")

    with gr.Tabs():
        # TAB 1 — MOST PROMINENT: the grounded clinical note
        with gr.Tab("🩺 Clinical Note"):
            gr.Markdown("_Editable — grounded strictly in what the patient said._")
            chief_complaint = gr.Textbox(label="Chief Complaint", lines=4, interactive=True)
            duration = gr.Textbox(label="Duration", lines=3, interactive=True)
            with gr.Row():
                severity = gr.Textbox(label="Severity", lines=3, interactive=True, scale=3)
                severity_badge = gr.HTML(label="", scale=1)
            history = gr.Textbox(label="Relevant History", lines=5, interactive=True)

        # TAB 2 — SECOND TIER: conservative AI-generated nudge
        with gr.Tab("💡 Possible Recommendations"):
            gr.Markdown(
                "_AI-suggested considerations for triage — editable. "
                "Not a diagnosis; hedged and conservative by design._"
            )
            possible_recommendations = gr.Textbox(
                label="Possible Causes / Effects / Considerations",
                lines=8,
                interactive=True
            )

        # TAB 3 — MINOR, de-emphasized reference only
        with gr.Tab("🔑 Keywords (reference)"):
            gr.Markdown("_Quick-scan reference only — not part of the saved clinical note._")
            keywords_display = gr.Textbox(
                label="Extracted keywords",
                lines=12,
                interactive=False
            )

    # --- Step 3: Save ---
    with gr.Group():
        gr.Markdown("### 💾 Step 3 — Save to Patient History")
        save_btn = gr.Button("Save Patient Record to Database", variant="primary", size="lg")
        save_status = gr.Textbox(label="Save Status", interactive=False)

    # --- Patient history lookup ---
    with gr.Group():
        gr.Markdown("### 📖 View Patient Clinical History")
        history_btn = gr.Button("View History for This Patient ID")
        history_display = gr.Textbox(label="Past Visits", lines=8, interactive=False)

    # ------------------------------------------------------------------
    # Wire up the pipeline
    # ------------------------------------------------------------------

    transcribe_btn.click(
        fn=process_patient_intake,
        inputs=[patient_id, language, audio_input],
        outputs=[
            chief_complaint, duration, severity, history, severity_badge,
            possible_recommendations, keywords_display,
            transcript_state, keywords_state, process_status
        ]
    )

    save_btn.click(
        fn=handle_save_click,
        inputs=[
            patient_id, language, chief_complaint, duration, severity, history,
            possible_recommendations, transcript_state, keywords_state
        ],
        outputs=[save_status]
    )

    history_btn.click(
        fn=handle_view_history_click,
        inputs=[patient_id],
        outputs=[history_display]
    )

if __name__ == "__main__":
    # share=True gives a public https://xxxx.gradio.live link — needed since
    # this runs on Colab's server, not your own machine. Link lasts ~72 hours.
    demo.launch(share=True, debug=True)
