{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyMOfN0YzjDu1X96bXCUEF6M"
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "source": [
        "Imports and Configuration"
      ],
      "metadata": {
        "id": "fiNidPI7NBQv"
      }
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "dD77uE_XMl6l"
      },
      "outputs": [],
      "source": [
        "\"\"\"\n",
        "Language Identification Stage\n",
        "\n",
        "Uses Meta's MMS Language Identification model to identify\n",
        "whether a patient's audio is spoken in Hausa, Igbo, or Yoruba.\n",
        "\n",
        "This module only identifies the language.\n",
        "Transcription is handled separately by asr/transcribe.py.\n",
        "\"\"\"\n",
        "\n",
        "# ============================================================\n",
        "# IMPORT LIBRARIES AND CONFIGURATION\n",
        "# ============================================================\n",
        "\n",
        "import torch\n",
        "from transformers import pipeline\n",
        "\n",
        "\n",
        "# Meta's multilingual speech language identification model.\n",
        "MMS_MODEL = \"facebook/mms-lid-126\"\n",
        "\n",
        "\n",
        "# These are the only languages currently supported by our app.\n",
        "# MMS uses language codes, so we map them to our language names.\n",
        "SUPPORTED_LANGUAGES = {\n",
        "    \"hau\": \"Hausa\",\n",
        "    \"ibo\": \"Igbo\",\n",
        "    \"yor\": \"Yoruba\",\n",
        "}\n",
        "\n",
        "\n",
        "# Use the GPU if one is available.\n",
        "# Otherwise, use the CPU.\n",
        "device = 0 if torch.cuda.is_available() else -1"
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "Loading the MMS model"
      ],
      "metadata": {
        "id": "U7S7VQyGNCcg"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "# Load the MMS language identification model.\n",
        "# This model is used only for identifying the language.\n",
        "#\n",
        "# The model is loaded once and reused instead of loading it\n",
        "# every time a recording is processed.\n",
        "\n",
        "print(\"Loading MMS LID model...\")\n",
        "\n",
        "lid_pipeline = pipeline(\n",
        "    \"audio-classification\",\n",
        "    model=MMS_MODEL,\n",
        "    device=DEVICE\n",
        ")\n",
        "\n",
        "print(\"MMS LID loaded successfully.\")"
      ],
      "metadata": {
        "id": "EvO2smzgNC4V"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "source": [
        "Language detection function"
      ],
      "metadata": {
        "id": "tfl7bDVONDUl"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "# ============================================================\n",
        "# LANGUAGE DETECTION\n",
        "# ============================================================\n",
        "\n",
        "def detect_language(audio_path: str):\n",
        "    \"\"\"\n",
        "    Detect the spoken language in an audio recording.\n",
        "\n",
        "    MMS returns several language predictions. We only use\n",
        "    MMS's top prediction instead of selecting a supported\n",
        "    language from lower-ranked predictions.\n",
        "\n",
        "    This prevents the system from routing audio to an ASR\n",
        "    model when MMS actually predicted another language.\n",
        "\n",
        "    Returns:\n",
        "        language - Detected supported language or None\n",
        "        confidence - Confidence of the top prediction\n",
        "        results - Full MMS prediction results\n",
        "    \"\"\"\n",
        "\n",
        "    # Get the top 5 language predictions from MMS.\n",
        "    results = lid_pipeline(audio_path, top_k=5)\n",
        "\n",
        "    # MMS's first result is its highest-confidence prediction.\n",
        "    top_prediction = results[0]\n",
        "\n",
        "    language_code = top_prediction[\"label\"]\n",
        "    confidence = top_prediction[\"score\"]\n",
        "\n",
        "\n",
        "    # Check whether MMS's top prediction is one of the\n",
        "    # languages supported by our application.\n",
        "    if language_code in SUPPORTED_LANGUAGES:\n",
        "\n",
        "        return (\n",
        "            SUPPORTED_LANGUAGES[language_code],\n",
        "            confidence,\n",
        "            results\n",
        "        )\n",
        "\n",
        "\n",
        "    # MMS predicted a language that our application does not support.\n",
        "    return None, confidence, results"
      ],
      "metadata": {
        "id": "F2TUdh4BNGXt"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "source": [
        "Fallback function"
      ],
      "metadata": {
        "id": "jO882SSpNID_"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "def get_language_for_asr(audio_path: str):\n",
        "    \"\"\"\n",
        "    Detect the language and decide whether the audio can be\n",
        "    safely sent to one of the supported NCAIR ASR models.\n",
        "\n",
        "    If MMS detects Hausa, Igbo, or Yoruba:\n",
        "        Return the detected language.\n",
        "\n",
        "    If MMS detects an unsupported language:\n",
        "        Return None so the application can use its fallback.\n",
        "    \"\"\"\n",
        "\n",
        "    language, confidence, results = detect_language(audio_path)\n",
        "\n",
        "    # If a supported language was detected, use it for ASR.\n",
        "    if language is not None:\n",
        "        return language, confidence, results\n",
        "\n",
        "    # No supported language was detected.\n",
        "    # The caller can decide how to handle the recording.\n",
        "    return None, None, results"
      ],
      "metadata": {
        "id": "6EjByYJLNIct"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "# Download the LID code as a Python file.\n",
        "!jupyter nbconvert --to script lid.ipynb --output lid.py"
      ],
      "metadata": {
        "id": "XTm9x1-hXAea",
        "outputId": "516499a8-5e74-4f7f-88a9-14525ce8802c",
        "colab": {
          "base_uri": "https://localhost:8080/"
        }
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "[NbConvertApp] WARNING | pattern 'lid.ipynb' matched no files\n",
            "This application is used to convert notebook files (*.ipynb)\n",
            "        to various other formats.\n",
            "\n",
            "        WARNING: THE COMMANDLINE INTERFACE MAY CHANGE IN FUTURE RELEASES.\n",
            "\n",
            "Options\n",
            "=======\n",
            "The options below are convenience aliases to configurable class-options,\n",
            "as listed in the \"Equivalent to\" description-line of the aliases.\n",
            "To see all configurable class-options for some <cmd>, use:\n",
            "    <cmd> --help-all\n",
            "\n",
            "--debug\n",
            "    set log level to logging.DEBUG (maximize logging output)\n",
            "    Equivalent to: [--Application.log_level=10]\n",
            "--show-config\n",
            "    Show the application's configuration (human-readable format)\n",
            "    Equivalent to: [--Application.show_config=True]\n",
            "--show-config-json\n",
            "    Show the application's configuration (json format)\n",
            "    Equivalent to: [--Application.show_config_json=True]\n",
            "--generate-config\n",
            "    generate default config file\n",
            "    Equivalent to: [--JupyterApp.generate_config=True]\n",
            "-y\n",
            "    Answer yes to any questions instead of prompting.\n",
            "    Equivalent to: [--JupyterApp.answer_yes=True]\n",
            "--execute\n",
            "    Execute the notebook prior to export.\n",
            "    Equivalent to: [--ExecutePreprocessor.enabled=True]\n",
            "--allow-errors\n",
            "    Continue notebook execution even if one of the cells throws an error and include the error message in the cell output (the default behaviour is to abort conversion). This flag is only relevant if '--execute' was specified, too.\n",
            "    Equivalent to: [--ExecutePreprocessor.allow_errors=True]\n",
            "--stdin\n",
            "    read a single notebook file from stdin. Write the resulting notebook with default basename 'notebook.*'\n",
            "    Equivalent to: [--NbConvertApp.from_stdin=True]\n",
            "--stdout\n",
            "    Write notebook output to stdout instead of files.\n",
            "    Equivalent to: [--NbConvertApp.writer_class=StdoutWriter]\n",
            "--inplace\n",
            "    Run nbconvert in place, overwriting the existing notebook (only\n",
            "            relevant when converting to notebook format)\n",
            "    Equivalent to: [--NbConvertApp.use_output_suffix=False --NbConvertApp.export_format=notebook --FilesWriter.build_directory=]\n",
            "--clear-output\n",
            "    Clear output of current file and save in place,\n",
            "            overwriting the existing notebook.\n",
            "    Equivalent to: [--NbConvertApp.use_output_suffix=False --NbConvertApp.export_format=notebook --FilesWriter.build_directory= --ClearOutputPreprocessor.enabled=True]\n",
            "--coalesce-streams\n",
            "    Coalesce consecutive stdout and stderr outputs into one stream (within each cell).\n",
            "    Equivalent to: [--NbConvertApp.use_output_suffix=False --NbConvertApp.export_format=notebook --FilesWriter.build_directory= --CoalesceStreamsPreprocessor.enabled=True]\n",
            "--no-prompt\n",
            "    Exclude input and output prompts from converted document.\n",
            "    Equivalent to: [--TemplateExporter.exclude_input_prompt=True --TemplateExporter.exclude_output_prompt=True]\n",
            "--no-input\n",
            "    Exclude input cells and output prompts from converted document.\n",
            "            This mode is ideal for generating code-free reports.\n",
            "    Equivalent to: [--TemplateExporter.exclude_output_prompt=True --TemplateExporter.exclude_input=True --TemplateExporter.exclude_input_prompt=True]\n",
            "--allow-chromium-download\n",
            "    Whether to allow downloading chromium if no suitable version is found on the system.\n",
            "    Equivalent to: [--WebPDFExporter.allow_chromium_download=True]\n",
            "--disable-chromium-sandbox\n",
            "    Disable chromium security sandbox when converting to PDF..\n",
            "    Equivalent to: [--WebPDFExporter.disable_sandbox=True]\n",
            "--show-input\n",
            "    Shows code input. This flag is only useful for dejavu users.\n",
            "    Equivalent to: [--TemplateExporter.exclude_input=False]\n",
            "--embed-images\n",
            "    Embed the images as base64 dataurls in the output. This flag is only useful for the HTML/WebPDF/Slides exports.\n",
            "    Equivalent to: [--HTMLExporter.embed_images=True]\n",
            "--sanitize-html\n",
            "    Whether the HTML in Markdown cells and cell outputs should be sanitized..\n",
            "    Equivalent to: [--HTMLExporter.sanitize_html=True]\n",
            "--log-level=<Enum>\n",
            "    Set the log level by value or name.\n",
            "    Choices: any of [0, 10, 20, 30, 40, 50, 'DEBUG', 'INFO', 'WARN', 'ERROR', 'CRITICAL']\n",
            "    Default: 30\n",
            "    Equivalent to: [--Application.log_level]\n",
            "--config=<Unicode>\n",
            "    Full path of a config file.\n",
            "    Default: ''\n",
            "    Equivalent to: [--JupyterApp.config_file]\n",
            "--to=<Unicode>\n",
            "    The export format to be used, either one of the built-in formats\n",
            "            ['asciidoc', 'custom', 'html', 'latex', 'markdown', 'notebook', 'pdf', 'python', 'qtpdf', 'qtpng', 'rst', 'script', 'slides', 'webpdf']\n",
            "            or a dotted object name that represents the import path for an\n",
            "            ``Exporter`` class\n",
            "    Default: ''\n",
            "    Equivalent to: [--NbConvertApp.export_format]\n",
            "--template=<Unicode>\n",
            "    Name of the template to use\n",
            "    Default: ''\n",
            "    Equivalent to: [--TemplateExporter.template_name]\n",
            "--template-file=<Unicode>\n",
            "    Name of the template file to use\n",
            "    Default: None\n",
            "    Equivalent to: [--TemplateExporter.template_file]\n",
            "--theme=<Unicode>\n",
            "    Template specific theme(e.g. the name of a JupyterLab CSS theme distributed\n",
            "    as prebuilt extension for the lab template)\n",
            "    Default: 'light'\n",
            "    Equivalent to: [--HTMLExporter.theme]\n",
            "--sanitize_html=<Bool>\n",
            "    Whether the HTML in Markdown cells and cell outputs should be sanitized.This\n",
            "    should be set to True by nbviewer or similar tools.\n",
            "    Default: False\n",
            "    Equivalent to: [--HTMLExporter.sanitize_html]\n",
            "--writer=<DottedObjectName>\n",
            "    Writer class used to write the\n",
            "                                        results of the conversion\n",
            "    Default: 'FilesWriter'\n",
            "    Equivalent to: [--NbConvertApp.writer_class]\n",
            "--post=<DottedOrNone>\n",
            "    PostProcessor class used to write the\n",
            "                                        results of the conversion\n",
            "    Default: ''\n",
            "    Equivalent to: [--NbConvertApp.postprocessor_class]\n",
            "--output=<Unicode>\n",
            "    Overwrite base name use for output files.\n",
            "                Supports pattern replacements '{notebook_name}'.\n",
            "    Default: '{notebook_name}'\n",
            "    Equivalent to: [--NbConvertApp.output_base]\n",
            "--output-dir=<Unicode>\n",
            "    Directory to write output(s) to. Defaults\n",
            "                                  to output to the directory of each notebook. To recover\n",
            "                                  previous default behaviour (outputting to the current\n",
            "                                  working directory) use . as the flag value.\n",
            "    Default: ''\n",
            "    Equivalent to: [--FilesWriter.build_directory]\n",
            "--reveal-prefix=<Unicode>\n",
            "    The URL prefix for reveal.js (version 3.x).\n",
            "            This defaults to the reveal CDN, but can be any url pointing to a copy\n",
            "            of reveal.js.\n",
            "            For speaker notes to work, this must be a relative path to a local\n",
            "            copy of reveal.js: e.g., \"reveal.js\".\n",
            "            If a relative path is given, it must be a subdirectory of the\n",
            "            current directory (from which the server is run).\n",
            "            See the usage documentation\n",
            "            (https://nbconvert.readthedocs.io/en/latest/usage.html#reveal-js-html-slideshow)\n",
            "            for more details.\n",
            "    Default: ''\n",
            "    Equivalent to: [--SlidesExporter.reveal_url_prefix]\n",
            "--nbformat=<Enum>\n",
            "    The nbformat version to write.\n",
            "            Use this to downgrade notebooks.\n",
            "    Choices: any of [1, 2, 3, 4]\n",
            "    Default: 4\n",
            "    Equivalent to: [--NotebookExporter.nbformat_version]\n",
            "\n",
            "Examples\n",
            "--------\n",
            "\n",
            "    The simplest way to use nbconvert is\n",
            "\n",
            "            > jupyter nbconvert mynotebook.ipynb --to html\n",
            "\n",
            "            Options include ['asciidoc', 'custom', 'html', 'latex', 'markdown', 'notebook', 'pdf', 'python', 'qtpdf', 'qtpng', 'rst', 'script', 'slides', 'webpdf'].\n",
            "\n",
            "            > jupyter nbconvert --to latex mynotebook.ipynb\n",
            "\n",
            "            Both HTML and LaTeX support multiple output templates. LaTeX includes\n",
            "            'base', 'article' and 'report'.  HTML includes 'basic', 'lab' and\n",
            "            'classic'. You can specify the flavor of the format used.\n",
            "\n",
            "            > jupyter nbconvert --to html --template lab mynotebook.ipynb\n",
            "\n",
            "            You can also pipe the output to stdout, rather than a file\n",
            "\n",
            "            > jupyter nbconvert mynotebook.ipynb --stdout\n",
            "\n",
            "            PDF is generated via latex\n",
            "\n",
            "            > jupyter nbconvert mynotebook.ipynb --to pdf\n",
            "\n",
            "            You can get (and serve) a Reveal.js-powered slideshow\n",
            "\n",
            "            > jupyter nbconvert myslides.ipynb --to slides --post serve\n",
            "\n",
            "            Multiple notebooks can be given at the command line in a couple of\n",
            "            different ways:\n",
            "\n",
            "            > jupyter nbconvert notebook*.ipynb\n",
            "            > jupyter nbconvert notebook1.ipynb notebook2.ipynb\n",
            "\n",
            "            or you can specify the notebooks list in a config file, containing::\n",
            "\n",
            "                c.NbConvertApp.notebooks = [\"my_notebook.ipynb\"]\n",
            "\n",
            "            > jupyter nbconvert --config mycfg.py\n",
            "\n",
            "To see all available configurables, use `--help-all`.\n",
            "\n"
          ]
        }
      ]
    }
  ]
}